### ISSUE TITLE
error running example and game on kde neon

### ISSUE THREAD

**Issue by 22i** [Aaron-SP/bds#1]
i am running kde neon ubuntu 16.04 xenial xerus

sucessfully got g++ 6 to work with https://askubuntu.com/questions/781972/how-can-i-update-gcc-5-3-to-6-1/781977

my gcc version is 6.4.0 20180424 (Ubuntu 6.4.0-17ubuntu1~16.04)

with the script fglrx.sh i successfully installed libva-glx1 libva-egl1 vainfo packages
but could not install fglrx-updates E: Package 'fglrx-updates' has no installation candidate
and xvba-va-driver E: Unable to locate package xvba-va-driver

ran make example1 successfully with no errors but when i try to run ex1 in bin in terminal it shows:

x_window: opening X11 opengl context version 3.3 shader: minimum extensions not met

building bds did not make any errors but running game in terminal shows:

terminate called after throwing an instance of 'std::runtime_error'
  what():  mem_chunk: could not read file 'data/data.sky

**Comment by Aaron-SP** [comment]
Sorry I should have seen this sooner. There are multiple issues here so let me try to simplify with a list.

1). The fglrx.sh script is only useful for installing proprietary graphics card drivers on AMD GPU hardware and was discontinued after Ubuntu 14.04. What GPU hardware are you using?

2). "shader: minimum extensions not met" means that gl_arb_vertex_shader, gl_arb_fragment_shader, or gl_arb_geometry_shader4 are not defined on the system. Likely the OpenGL implementation is missing geometry shader support which was introduced in OpenGL 3.2.

3). Make sure you execute the binary in the project root directory with "bin/game", as it looks for the data directory and assumes the current working directory is the project root, i.e not inside the bin directory.

To query your OpenGL capability run these commands.

sudo apt install mesa-utils
glxinfo | grep "OpenGL version"

My guess is that you are using the open source drivers and these are not sufficient in providing OpenGL 3.3 capability for your GPU hardware. Please post GPU hardware to confirm.

**Comment by 22i** [comment]
tried running `"bin/game"` from root game directory and same thing happened

not sure what GPU hardware i am using but with `neofetch` command it says i am using Intel Sandybridge Mobile

after running [lspci](https://www.cyberciti.biz/faq/linux-tell-which-graphics-vga-card-installed/) `lspci | grep -i --color 'vga\|3d\|2d'`
Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)

after running `glxinfo | grep "OpenGL version"` i got: OpenGL version string: 3.0 Mesa 17.2.8

**Comment by Aaron-SP** [comment]
1) Check that a data/data.sky file exists, then check the permissions on the entire directory. For some reason the executable can't open that file which holds all the game textures, models, sound files etc.

2) OpenGL version string: 3.0 Mesa 17.2.8 is not high enough to play the game. 

You need at least OpenGL version string: 3.3 to play. The game doesn't support legacy OpenGL, mainly because OpenGL 3.3 is over 10 years old and other software like Blender will be dropping legacy support in their upcoming 2.8 version. The only solution is to try to find a way to upgrade your GPU drivers or switch to a computer that supports it. I would look around for what Ubuntu provides for Intel drivers and see if there is a proprietary Intel driver you can use (if you want to use it of course, some people don't want to).

Its frustrating but that is the current state of OpenGL on Linux for older hardware.

**Comment by Aaron-SP** [comment]
You should try to pull the latest MGL and BDS. There was a bug with the way I was handling OpenGL extension detection which may have resulted in this error and I wrongfully declared it a driver issue.

**Comment by 22i** [comment]
i remade every step with the latest Building Beyond Dying Skies on Ubuntu! [https://www.youtube.com/watch?v=7z46_webK90&t=273s](url) and it works now!

**Comment by Aaron-SP** [comment]
Glad to hear it is working for you! I will close out this issue.
