### ISSUE TITLE
Controls Menu

### ISSUE THREAD

**Issue by ocket8888** [Aaron-SP/bds#10]
It'd be nice to have customize-able controls. Currently the keybinds are hard-coded, but there are two blank menu tiles in the pause menu, one of which could easily say "Controls" and allow custom keybinds. As a dvorak keymap user, the game isn't truly playable atm unless I change my layout, so I'd like to see this change.

**Comment by ocket8888** [comment]
Doing this isn't as trivial as it seems at first glance, I started working on a patch before I realized it would require deep changes to the game engine. First, the system of specifying the game's state as one of 'Paused', 'Title' or 'Running' isn't conducive to nested menus in either the pause menu or title screen, but a deeper issue is that menus ought to be abstracted so that arbitrary entries can be added to create unique objects. Furthermore, it'd be ideal to show the current keybind next to the button to change it, which is something for which the current menu system isn't built. Finally, keybinds are currently hard-coded, and in order to support persistent keybinds, a system should be in place to instead read those in from some configuration file, written when keybinds are updated.

**Comment by Aaron-SP** [comment]
I am planning to do this. I want to add keybinding support in the menu to allow changing keys on demand.

The first thing I need, since you have a DVORAK keyboard is to look at https://github.com/Aaron-SP/mgl/blob/master/source/platform/min/x_window.h and see if we have all keys in the key code enum that are important.

win32_window.h also needs to be the same if you want to add any new keys to the list.

**Comment by Aaron-SP** [comment]
The menu is probably impossible to modify, unless you are me and then it is pretty easy. Basically all UI elements share the same pool of RAM & GPU memory, so you need to create a menu controller and then add a new menu state to the game. I can do this today.

I will have to persist the key bindings in the state file which should be easy to add. I can do this today.

Just keep in mind that I have a run target which is the equivalent of a t100 asus transformer. I have to preallocate the amount of GPU memory before the game launches so I have stricter constraints. 

I don't know how to manually abstract the menu system when you have to manually calculate the memory offset of each UI element.

**Comment by ocket8888** [comment]
I was able to get far enough to have one of the blank tiles read "Controls" and then print something to stdout when you click it, but it was at about that point that I realized going further would require making changes to things I didn't understand :P . With the number of keys that can be bound you may have to implement menu scrolling, unfortunately. Number keys and function keys can likely be left out of an initial attempt, though.

**Comment by ocket8888** [comment]
Looking at the mgl file you linked, it seems that support would need to be added for the `'` (apostrophe), `,` (comma), `.` (period) and `;` (semicolon) keys in order to support a traditional WASD-QE-ZXC control scheme (`w` -> `,`, `q`->`'`, `e`->`.`, `z`->`;`). I think - but am not sure - that AZERTY can be sufficiently supported with the keys you currently support.

**Comment by Aaron-SP** [comment]
I will try to get everything done for switching keys today. For now I will ignore DVORAK and just get the ability to switch keys in the menu. Then I can extend it for DVORAK support afterwards. The menu will be like a table, so no need for scrolling.

I don't have a DVORAK keyboard nor understand how it works, so if you have any good resources to point me in a good direction it would be appreciated.

**Comment by ocket8888** [comment]
Here's a side-by-side comparison:

![qwerty vs dvorak](https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2Fthekindle3books.com%2Fwp-content%2Fuploads%2F2017%2F03%2FQWERTY-vs-Dvorak-The-two-great-keyboards-the-time-were-born-2.png&f=1)

My actual keyboard is just your average plastic Dell piece of garbage, it's just that what each key _means_ has been changed around a little. AZERTY is somewhat more popular than Dvorak (I think), and is much the same way. Neither of them afaik modify control keys like e.g. caps lock, alt, super.

**Comment by Aaron-SP** [comment]
Checkout out https://github.com/Aaron-SP/mgl/commit/6fd433d2207f683eeb87a5885cdd5138cdee1520 and https://github.com/Aaron-SP/bds/commit/2479175b3928c1dfc2afbba03912dcdeb9794c09. Key remapping should work but it isn't pretty. I need to add labels and figure out a way to order the keys in the UI consistently.

Play around with it and see if there are any major bugs. 

I still need to extend the MGL key codes for the DVORAK key list.

**Comment by ocket8888** [comment]
Looks good so far. Even handles unimplemented keys better than I thought it would.

**Comment by Aaron-SP** [comment]
So if you press a key, does it respond with the correct key string? Say if you press P on your DVORAK keyboard, it registers as a P in the key string?

**Comment by ocket8888** [comment]
Yeah, it's working properly. You can probably test it yourself, idk what distro/DE you're using, but in most of them you can just go to 'Keyboard' in the provided settings menu and select a layout like e.g. Dvorak. Or if it's just a barebones X11 environment, open a terminal emulator and put in `setxkbmap dvorak` and to switch back to QWERTY (US) use `setxkbmap us`. Of course, that means you'd need to be able to type in dvorak, but that keyboard layout comparison should help, if you wanna go that route.

**Comment by Aaron-SP** [comment]
The latest mgl:master and bds:dev now order the key controls in a neat ordering and have labels. I am going to persist the key mappings in the state file, and I will add a --dvorak runtime command to default the key mapping to DVORAK style. Basically the same physical keys as for QWERTY.

**Comment by ocket8888** [comment]
Everything seems to be working fine. I can't test persistence across multiple loads, however, due to permission errors on the directory to which it's trying to save the state.

**Comment by Aaron-SP** [comment]
I am going to change the save directory to $ROOT/save instead of $ROOT/bin. The 'make install' target 755's the entire directory for security reasons. chmod 777 $ROOT/save should be safe but obviously chmod 777 $ROOT/bin is not a good idea. It will be fixed in the next patch, hopefully in a few hours.

**Comment by Aaron-SP** [comment]
The latest mgl:master and bds:dev now give DVORAK key maps first class support. The README has usage info but you can do 'bin/game --dvorak --no-persist' to force load DVORAK settings. It should be easy to extend further keymap layouts in the future.

The save issue should be fixed, but I haven't thoroughly tested on all systems yet. 

I am going to go do some testing since I am sure there are still a few bugs to find.

**Comment by Aaron-SP** [comment]
Alright I did some cleaning up with the repo. https://github.com/Aaron-SP/mgl/commit/b4bd522e5ced1f1a6bc9951ad4e8bb609f4c74ef and https://github.com/Aaron-SP/bds/commit/5fe26d123547cea4adfcc69d51d2a2315891bd36 should be feature complete as I understand it. I did heavy rebasing, so toss any old history and start over with the master branch.

**Comment by ocket8888** [comment]
Key remapping works perfectly. However no controls are allowed to be unbound at any point, which means if you want a key to do something else you must first reassign the control to which it is currently bound. That's not a problem, just not what I'd expect given my past experiences with control mapping.

The `--dvorak` option appears to function as intended, but if the controls are manually edited and then the game is relaunched using `--dvorak` the manually bound keys override Dvorak unless `--no-persist` is also given. Again, could just be an intentional design decision.

**Comment by Aaron-SP** [comment]
The --dvorak and --qwerty just set the default mapping. The keymap file, if it exists, will override these default mappings. If you manually set an unsupported key, it will be saved to the keymap as "???" and thus you will need the default mapping to fall back on. Hints why there is a --dvorak and --no-persist. The keymap file is an ASCII text file. You can edit it manually if needed but these are case sensitive at the moment.

The reason you can set an unsupported key, yet it doesn't persist in the keymap file is because I need a common string to translate the numerical key code to and this is different between platforms. Thus I need to set it in the enum list to be a valid key code.

Maybe it should be different, I don't know right now.

**Comment by ocket8888** [comment]
Well in that case I think we can safely call this closed.
