### ISSUE TITLE
install target missing

### ISSUE THREAD

**Issue by jellelicht** [Aaron-SP/bds#4]
It seems that one can currently not easily install the game to a custom location.
Are there any plans to move to a build system that supports this, e.g. the gnu auto-tools, or something similar?

**Comment by Aaron-SP** [comment]
I don't understand. The game should run anywhere since all the files are self contained in the project root. You can change the location of the MGL with the $(MGL_DESTDIR) variable in the make file. Look at how I do it in Arch [here](https://github.com/Aaron-SP/pkgbuild/blob/master/bds/PKGBUILD). I put it in /opt but you could put it any where.

The current layout isn't necessarily permanent and I am open to suggestions.

**Comment by jellelicht** [comment]
To rephrase: It would be nice to be able to issue a simple `make install` (with potential stuff like DESTDIR and what not) to install the game.

**Comment by Aaron-SP** [comment]
I added an install and uninstall target to the makefile in commit 327b88b9ef577483b37bb047a5faad9b705e8cdb. The default install directory is /opt/bds.

Usage:
make install
make DESTDIR=/opt/test install

The makefile will generate a bash script that captures DESTDIR inside of it, so you can run the game with 'bds.game' which is a symlink to the generated bash script. The '.game' suffix was added to avoid any name naming collisions. The symlink 'bds.game' is placed into /usr/bin/. I considered adding a way to override this but left it out for now.

Possible conflicts arise if a naming conflict exists between 'bds.game' or '/opt/bds'.

**Comment by Aaron-SP** [comment]
I am going to close this issue. If you have problems with the usage, open a new issue.
