### ISSUE TITLE
Looking up quickly causes my character to spin randomly to a position 

### ISSUE THREAD

**Issue by godofgrunts** [Aaron-SP/bds#7]
If I look directly upwards really fast my character will suddenly spin and then spot as if I am unable to look straight up when facing certain directions.

**Comment by Aaron-SP** [comment]
This is a special case because looking straight up, or straight down is undefined behavior. In this case the forward vector is equal to the up vector on the camera, and you can't calculate a right vector by taking the cross product of the forward and the up vector, so I just set it to (1.0, 0.0, 0.0) as a fail safe. However, this will cause you to "spin" or align with the X axis.

There is probably a better way to recover from this error. I will think about it tonight.

**Comment by Aaron-SP** [comment]
Alright, so I added head tracking to the camera in MGL commit https://github.com/Aaron-SP/mgl/commit/0e4441783d0e9179c0521e176697308de3766b0f, which removes the undefined behavior in the camera class. You can now do "backflips". That isn't technically a bug, although could be uncomfortable on first use. 

You also need BDS commit https://github.com/Aaron-SP/bds/commit/122ad1ee1e55f81ad0c7986b39e6506a58ffeb9d. 

Trying to limit the player field of view just doesn't work well so I removed it. I kind of like it the way it is, but not sure what people would think of it. It isn't realistic, but could be useful.

**Comment by godofgrunts** [comment]
Sounds interesting. I'm fairly certain it'll be disorienting, but I'll rebuild tomorrow and give it a go.

**Comment by Aaron-SP** [comment]
I've been testing it and it seems to work decently for me. I am going to close out this issue in the next few days unless I hear back from you.

**Comment by godofgrunts** [comment]
Sorry, I don't usually have a ton of free time and it's been even less than usual the past few days. You can close if you want, I'll get around to testing eventually.
