### ISSUE TITLE
Icon?

### ISSUE THREAD

**Issue by ocket8888** [Aaron-SP/bds#8]
Do you have like an icon or symbol for the game anywhere?

**Comment by Aaron-SP** [comment]
I can make one using the title screen images, but I am not sure how it would look in a small icon. Why do you need one, what size and what format?

**Comment by ocket8888** [comment]
I wanted to make a `.desktop` entry for the game, and it'd be nice to have an icon. It'd probably be best to have it in Scalable Vector Graphic format, so that you can easily export icons for various-sized UI scales. I wouldn't be opposed to drafting one myself, if you'd like.

**Comment by ocket8888** [comment]
I was also gonna submit a PR that adds it to the install target when other `.desktop` files are found under `/usr/share/applications/` on *nix systems.

**Comment by Aaron-SP** [comment]
If you want to make an icon go for it and maybe it would give me some ideas. I am not a logo person. If I were going to make one it might be a planet but I am not sure how that would look as a simple SVG.

**Comment by Aaron-SP** [comment]
I added a favicon to 6b55649022992c19871c208264b1309aa98876cf. It contains a 128, 64, 32, and 16 pixel icon. I used the planet from the title screen and it looks pretty good.

The make install target will copy the favicon file into $(DESTDIR). I created a .desktop file in the root of the BDS repository which you should be able to copy onto your desktop, enable execution and run the program without issue. I tested this on Ubuntu 14.04.

Since the favicon is in the same folder as the game files, we shouldn't have to mess around with the /usr/share/icons folder do we?

Let me know if that is good enough for you.

**Comment by ocket8888** [comment]
Yeah, it should be fine to have the icon wherever as long as its location is specified absolutely within the `bds.desktop` file. I did wind up making that pull request to install that file, [PR #9](https://github.com/Aaron-SP/bds/pull/9). I also think I'll probably wind up making an icon source svg and posting it here.

**Comment by Aaron-SP** [comment]
I am closing this out now since I merged the pull request.
